### ISSUE TITLE
Nodemailer Example

### ISSUE THREAD

**Issue by ghost** [analog-nico/pxl-for-emails#1]
hey nice work but can you provide us with full example with node nodemailer??

thanks for awesome work

**Comment by analog-nico** [comment]
Quite simple:

Take the example from [nodemailer.com](https://nodemailer.com):

``` js
const nodemailer = require('nodemailer')

let transporter = nodemailer.createTransport({ ... })

let mailOptions = {
    ...
    html: emailMarkup
}

transporter.sendMail(mailOptions, (error, info) => { ... })
```

Before that create `emailMarkup` like described in the [README](https://github.com/analog-nico/pxl-for-emails#what-for):

``` js
let emailMarkup = generateHtmlEmail()

emailMarkup = pxlForEmails.addTracking(emailMarkup, { recipient: addressTo })
```

Hope this helps!

**Comment by ivanakruljac** [comment]
Hi! I found pxl-for-email exactly what I need.
I need to track if email is opened and if some url inside email is clicked. Then I need to do with data if this case is true.

With next code I'm sending the email to user and also I'm sending submitted data into MongoDB. I wanna track url in email and if email is opended. So, everything works, except I can't get this pixel to work. I can't see nothing in DB ... :(

I'm using nodemailer for sending emails, and my POST-endpoint looks like this:

```
let Pxl = require('pxl-mongodb');
let pxl = new Pxl();
pxl.connect('mongodb://);

const app = express()

app.use(pxl.trackPxl)

app.get('/shortly/:linkId', pxl.redirect)
let PxlForEmails = require('pxl-for-emails')
let pxlForEmails = new PxlForEmails({
    pxl,
    getFullShortenedLink(linkId) {
        return `http://localhost:3000/shortly/${ linkId }`
    }
})

app.post('/:form', function(req, res) {
    try {
        var conf = yaml.safeLoad(fs.readFileSync(path.join(APP_ROOT, '..', 'configs', req.params.form + ".yml")))
    } catch (e) {
        return res.sendStatus(404)
    }
     //--COLLECT SOME DATA
     var data = req.body
     data.cipid = req.query.cipid
     data.referrer = req.query.referrer
     data.klickstrecke_id = req.query.klickstrecke_id
     data.klickstrecke_keyword = req.query.klickstrecke_keyword
     data.klickstrecke_city = req.query.klickstrecke_city
   
  let emailMarkup = "<b><img src='https://www.marktplatz-mittelstand.de/infocenter/wp-content/themes/infocenter/assets/images/1pixel.png'/>Hello world, this is a test template <a href='https://www.marktplatz-mittelstand.de/infocenter/' target='_blank'>" + data.customer_data.first_name + "</a></b>";

     mailMarkup = pxlForEmails.addTracking(emailMarkup, { recipient: data.customer_data.email })

      nodeMailer.createTestAccount((err, account) => {
          let transporter = nodeMailer.createTransport({
              host: 'smtp.gmail.com',
              port: 465,
              secure: true, 
              auth: {
                user: creds.user,
                pass: creds.pass
              }
          });
          // setup email data with unicode symbols
          let mailOptions = {
            from: '"Ivana Beni" , 
            to: data.customer_data.email
            subject: "Ihre Anfrage über " + conf.branch_name,
              html: emailMarkup
          };
          transporter.sendMail(mailOptions, (error, info) => {
              if (error) {
                  return console.log(error);
              }
              console.log('Message sent: %s', info.messageId);
          });
        });
           // send to MongoDB API
          MongoClient.connect(database.url, function(err, db) {
            if (err) throw err;
            var dbo = db.db("beni");
            dbo.collection('leads').insertOne(data, function(err, result) {
              if (err) throw err;
                //console.log(result);
              db.close();
            });
          });
  })
```


I'm frontend developer and just starting with node.js.

So, any kind of help would be welcome. This solution with pxl-for-emails sound perfect and simple, but I just can't get it to work.

**Comment by analog-nico** [comment]
@ivanakruljac I am glad to hear that. I am using this lib in production for over a year now and it works well for me.

I think your issue is really quite simple: Your HTML in the `emailMarkup` is not correct. Please use double quotes (") instead of single quotes (') in your links according to the HTML standard. Once you do this you’ll also see that the `mailMarkup` variable will contain altered markup with the tracking added to it.

**Comment by ivanakruljac** [comment]
Nice, thnx for this! Works now, well sort of :)
Few questions :)
When I send email, pixels and links get generated, but when I open email, or click on the link inside it, nothing happens. Am I misising something?

And many thanx for replay !

**Comment by ivanakruljac** [comment]
And one more thing :)
I'm using also mailer email template for sending some nice emails, like so:
```
          transporter.use('compile', hbs({
                viewPath:APP_ROOT + '/email-template',
                extName: '.hbs'
            }));
          let mailOptions = {
            from: '"Marktplatz Mittelstand" <kruljac.ivana.beni@gmail.com>',
            to: data.customer_data.email
            subject: "Ihre Anfrage über " + conf.branch_name,
              template: 'email-inline',
              context:{
                firstName: data.customer_data.first_name,
                lastName: data.customer_data.last_name,
                branchName: conf.branch_name
              }
          };
         emailMarkup = pxlForEmails.addTracking('email-inline', { recipient: data.customer_data.email })
```
So, can you help me with how can I attach pixels to this specific template?

**Comment by analog-nico** [comment]
@ivanakruljac You recognize that the tracking is correctly applied when the links have been replaced and one of your image urls has been replaced for open tracking. Please look into your `emailMarkup` variable and go from there. You’ll find everything you need in the documentation.

**Comment by ghost** [comment]
for me i face problem with no ads its detected pixel and block it .and if the pxl tracking open from gmail the ip will gmail proxy servers.

again thanks nico for nice work

**Comment by analog-nico** [comment]
Hey @hamzaahmad great to hear from you again! Yes, there are these kinds of limitations. There is nothing we can do about it since it is in the hands of the email providers. However, I designed the library in a way that when a click is tracked then also the email is tracked as being opened. This way you can more easily count opened emails even with these restrictions. Of course, some email opens where the person did not click a link may not be counted if the images are not shown by the email client. Just keep in mind that email opens cannot be perfectly tracked no matter how you implement email tracking.

**Comment by saikatharryc** [comment]
@analog-nico  in my case, links are storing in db , but unfortunately, i dont see any docs in `pxl`.
```
const link = await pxl.shorten("https://b8179d42.ngrok.io/static/tracker.png")
      let emailMarkup =campaigDetails.template+`<footer><img src=' https://b8179d42.ngrok.io/shortly/${link.linkId}?pxl=<created pxl>' /></footer>`;
     emailMarkup = await pxlForEmails.addTracking(emailMarkup, {
      recipient: i
    })
```
